# replica-count.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3

---

apiVersion: extensions/v1beta1
kind: Ingress
spec:
  rules:
  - host: petclinic-staging.talhasahin.me  
